### ISSUE TITLE
FROM / WHERE / IN - all in upper case

### ISSUE THREAD

**Issue by NikitaErmakSenla** [MishaMisnik/sf-senla-courses#1]
https://github.com/MishaMisnik/sf-senla-courses/blob/a1e193988bacc861e775dff61e063cda11079fc8/lecture_2.2/TouristManager.cls#L10

**Comment by MishaMisnik** [comment]
[TouristManager.cls](https://github.com/MishaMisnik/sf-senla-courses/blob/main/lecture_2.2/TouristManager.cls)
