### ISSUE TITLE
2.2 check if trips are not empty

### ISSUE THREAD

**Issue by NikitaErmakSenla** [MishaMisnik/sf-senla-courses#10]
https://github.com/MishaMisnik/sf-senla-courses/blob/a1e193988bacc861e775dff61e063cda11079fc8/lecture_2.2/CreateNewFlight.cls#L4

**Comment by MishaMisnik** [comment]
[CreateNewFlight.cls](https://github.com/MishaMisnik/sf-senla-courses/blob/main/lecture_2.2/CreateNewFlight.cls)
