### ISSUE TITLE
2.2 Bad paddings

### ISSUE THREAD

**Issue by NikitaErmakSenla** [MishaMisnik/sf-senla-courses#11]
https://github.com/MishaMisnik/sf-senla-courses/blob/a1e193988bacc861e775dff61e063cda11079fc8/lecture_2.2/CreateNewFlight.cls#L12

**Comment by MishaMisnik** [comment]
[CreateNewFlight.cls](https://github.com/MishaMisnik/sf-senla-courses/blob/main/lecture_2.2/CreateNewFlight.cls)
