### ISSUE TITLE
2.2.1 code formatting: paddings

### ISSUE THREAD

**Issue by NikitaErmakSenla** [MishaMisnik/sf-senla-courses#17]
https://github.com/MishaMisnik/sf-senla-courses/blob/a858fd178ff483bd61600246c138c5484accee2b/lecture_2.2/CreateNewFlight.cls#L3

**Comment by MishaMisnik** [comment]
fixes
I copy from the developer console and my indents fly off 2 times
what could it be connected with?

**Comment by NikitaErmakSenla** [comment]
Still relevant. Try online code formatter / prettier

**Comment by MishaMisnik** [comment]
Fixes
