### ISSUE TITLE
2.3.2 'check' flag

### ISSUE THREAD

**Issue by NikitaErmakSenla** [MishaMisnik/sf-senla-courses#34]
https://github.com/MishaMisnik/sf-senla-courses/blob/33014bbb4cb4cd6696ea73caf9cd4b74fb209aa2/lecture_2.3/TouristService.cls#L13

**Comment by NikitaErmakSenla** [comment]
1 'check' - bad naming
2 What is the goal? If to not iterate next if duplicates found previously, then you should use while(check). For anyway will iterate over next items

**Comment by MishaMisnik** [comment]
Fixes

**Comment by NikitaErmakSenla** [comment]
1. Flag is bad naming as well. 
2. Try to think about smt like this:
```
Iterator<Tourist__c> touristIterator = similarTourists.iterator();

while (!isDuplicate && touristIterator.hasNext()) {
```

**Comment by MishaMisnik** [comment]
Fixes
