### ISSUE TITLE
2.2 better to use Set<Integer> to avoid duplicates

### ISSUE THREAD

**Issue by NikitaErmakSenla** [MishaMisnik/sf-senla-courses#4]
https://github.com/MishaMisnik/sf-senla-courses/blob/a1e193988bacc861e775dff61e063cda11079fc8/lecture_2.2/TouristManager.cls#L15

**Comment by MishaMisnik** [comment]
[TouristManager.cls](https://github.com/MishaMisnik/sf-senla-courses/blob/main/lecture_2.2/TouristManager.cls)
