### ISSUE TITLE
Bad naming

### ISSUE THREAD

**Issue by ekevra** [MishaMisnik/sf-senla-courses#42]
https://github.com/MishaMisnik/sf-senla-courses/blob/39835cbf0b038babb5c3d500e5386e5bbb773e59/lecture_2.5/Task%20%232/BatchService.cls#L1

На проекте всегда есть десятки классов batch, поэтому даже если сервис, то называть его как сам батч + Service

**Comment by MishaMisnik** [comment]
Fixes
