### ISSUE TITLE
2.2 As duplicates should be marked new tourists

### ISSUE THREAD

**Issue by NikitaErmakSenla** [MishaMisnik/sf-senla-courses#8]
https://github.com/MishaMisnik/sf-senla-courses/blob/a1e193988bacc861e775dff61e063cda11079fc8/lecture_2.2/TouristService.cls#L12

**Comment by MishaMisnik** [comment]
[TouristService.cls](https://github.com/MishaMisnik/sf-senla-courses/blob/main/lecture_2.2/TouristService.cls)
