### ISSUE TITLE
2.2 no empty line before method and its annotation

### ISSUE THREAD

**Issue by NikitaErmakSenla** [MishaMisnik/sf-senla-courses#9]
https://github.com/MishaMisnik/sf-senla-courses/blob/a1e193988bacc861e775dff61e063cda11079fc8/lecture_2.2/CreateNewFlight.cls#L3

**Comment by MishaMisnik** [comment]
[CreateNewFlight.cls](https://github.com/MishaMisnik/sf-senla-courses/blob/main/lecture_2.2/CreateNewFlight.cls)
